### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by hbs22** [Puzzled-Hui/IMR-SummerSchool-Airway-2022#2]
Hello, Teacher Zhang:
I have downloaded the BAS dataset, and each case contains an input and a mask folder. The input folder has DICOM files, and the mask folder has nii.gz files. Your README file mentions that there is also a processed folder under each case, which contains three nii.gz file. Could you please tell me what processing has been done to the files in the processed folder?

**Comment by Puzzled-Hui** [comment]
Hi, Baishuo,

The processed folder is basically the preprocess procedure, including the HU truncation, lung region crop, and intensity normalization. All steps could be easily finished.
